name: Upload Wordle Build to S3

on:
  push:
    branches: [main]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' 

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Verify build
        run: |
          if [ ! -f target/*.jar ]; then
            echo "No JAR file found in target directory!"
            exit 1
          fi

      - name: Create deployment zip
        run: |
          mkdir -p deploy
          cp Procfile deploy/
          cp target/*.jar deploy/ 
          cd deploy
          zip -r ../app.zip ./*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp app.zip s3://${{ secrets.S3_BUCKET }}/app.zip

      - name: Cleanup
        run: |
          rm -rf deploy
          rm -f app.zip
